apiVersion: v1
kind: Service
metadata: 
  name: sahil-sandbox-service
spec:
  selector:
    app: sahil-sandbox
  # type: LoadBalancer
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000